controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /api/{version}
    requirements:
        version: v1|v2|v3

kernel:
    resource: ../../src/Kernel.php
    type: annotation
